name: Hourly CMK price extract
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  push:
    branches:
      - main
jobs:
  Hourly-CMK-Extract:
    runs-on: ubuntu-latest
    env:
      COINMARKETCAPKEY: ${{ secrets.COINMARKETCAPKEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python main.py -l
