name: Hourly CMK price extract
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
jobs:
  Hourly-CMK-Extract:
    runs-on: ubuntu-latest
    env:
      COINMARKETCAPKEY: ${{ secrets.COINMARKETCAPKEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - run: python -m pip install --upgrade pip
        - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          run: python main.py -l
