name: CMK Latest Hourly
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  push:
    branches:
      - main
jobs:
  Hourly-CMK-Extract:
    runs-on: ubuntu-latest
    env:
      COINMARKETCAPKEY: ${{ secrets.COINMARKETCAPKEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - name: Install requirements
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt
        - name: Download data
          run:
            python main.py -l
