name: Horly CMK price extract
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'
jobs:
  Hourly-CMK-Extract:
    runs-on: ubuntu-latest
    env:
      COINMARKETCAPKEY: ${{ secrets.COINMARKETCAPKEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - run: pip install -r requirements.txt
      - run: python main.py -l
